### ISSUE TITLE
JSON array response error

### ISSUE THREAD

**Issue by markdingram** [oliyh/martian#29]
`(:response-schemas handler)` fails with an error for this Swagger defn (as the array has no name):

```
"200": {
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/Device"
    }
  },
  "description": "all devices"
}
```

```
#error{:cause "Assert failed: (clojure.core/not (clojure.core/nil? s__1611__auto__))",
       :via [{:type java.lang.AssertionError,
              :message "Assert failed: (clojure.core/not (clojure.core/nil? s__1611__auto__))",
              :at [camel_snake_kebab.core$__GT_kebab_case_keyword invokeStatic "core.cljc" 21]}],
       :trace [[camel_snake_kebab.core$__GT_kebab_case_keyword invokeStatic "core.cljc" 21]
               [camel_snake_kebab.core$__GT_kebab_case_keyword doInvoke "core.cljc" 21]
               [clojure.lang.RestFn invoke "RestFn.java" 410]
               [martian.schema$make_schema invokeStatic "schema.cljc" 67]
               [martian.schema$make_schema invoke "schema.cljc" 47]
```

Workaround is to wrap the array in an object:
```
"200": {
  "schema": {
    "type": "object",
    "properties": {
      "devices": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Device"
        }
  }
}
```

**Comment by oliyh** [comment]
Thanks @markdingram

It already supports structures like this for requests so it shouldn't be too hard to make it work for responses too, I'll have a go and let you know when it's ready.

Cheers

**Comment by oliyh** [comment]
Hi @markdingram,

Try the latest snapshot build now, it should work as desired.

Thanks for sending through all these issues, I use it mostly with objects
rather than arrays so didn't realise they didn't work properly!

Cheers

On 7 Dec 2016 12:02 p.m., "Mark Ingram" <notifications@github.com> wrote:

(:response-schemas handler) fails with an error for this Swagger defn (as
the array has no name):

"200": {
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/Device"
    }
  },
  "description": "all devices"
}

#error{:cause "Assert failed: (clojure.core/not (clojure.core/nil?
s__1611__auto__))",
       :via [{:type java.lang.AssertionError,
              :message "Assert failed: (clojure.core/not
(clojure.core/nil? s__1611__auto__))",
              :at [camel_snake_kebab.core$__GT_kebab_case_keyword
invokeStatic "core.cljc" 21]}],
       :trace [[camel_snake_kebab.core$__GT_kebab_case_keyword
invokeStatic "core.cljc" 21]
               [camel_snake_kebab.core$__GT_kebab_case_keyword
doInvoke "core.cljc" 21]
               [clojure.lang.RestFn invoke "RestFn.java" 410]
               [martian.schema$make_schema invokeStatic "schema.cljc" 67]
               [martian.schema$make_schema invoke "schema.cljc" 47]

Workaround is to wrap the array in an object:

"200": {
  "schema": {
    "type": "object",
    "properties": {
      "devices": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Device"
        }
  }
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/oliyh/martian/issues/29>, or mute the thread

**Comment by markdingram** [comment]
I think arrays are frowned upon as it makes it harder to evolve the response (e.g. how to add pagination later?). Anyway I'll check to confirm they are now handled.
