### ISSUE TITLE
martian-test help please

### ISSUE THREAD

**Issue by orlin** [oliyh/martian#40]
Hi @oliyh,

I don’t remember if I found martian or pedestal-api first, but I’m trying to use them together as part of ephemeris-api [here on a branch](https://github.com/astrolin/ephemeris-api/tree/martian-test).  I don’t know if I’m badly calling `martian/bootstrap-swagger` or `martian/response-for`.  I’ve read most of what’s out there: posts, readme, examples, etc.  I’ll break it up into three points I could use help with.  The first one being what’s really tripping me.

1. The martian #readme [martian-test example](https://github.com/oliyh/martian#testing-with-martian-test) uses the pedestal-api example, but I don’t think it works against that, because I tried it and `swagger-definition` is not recognized.  I’ve worked out a ci deployments workflow and got test.astrolin.org ready for martian-test I just can’t figure out how to use it.

2.  I kind of copied testing a `core` namespace from spa-skeleton, but I’m thinking in the case of api without frontend I should perhaps be testing the `service` namespace...  What do you think?  I ask because these tests really run against a server rather than any namespace and I wonder if it matters at all?  But then for a service maybe the handlers become core - would you move the handlers of a bigger web service / api into a `core` namespace?

3. Is `midje` of any use with `martian-test`?

**Comment by oliyh** [comment]
Hi @orlin,

Great to hear you're using them together!

You're right, the story for `martian-test` isn't quite there yet, and the documentation is a bit misleading. If you look at the tests for `martian-test` you will see that the Swagger definition is stored locally rather than being requested from the real server. I have updated that example so that it works as advertised (you now update the interceptors rather than just supplying one).

I am in the process of improving the project a bit so that it is more straightforward to use, including an API for loading the Swagger definition off the remote server rather than wanting it locally. Once I've done that I'll update the docs with better real-world examples and hopefully you'll find it more straightforward.

If you are testing the API I would just call it `api-test`, it denotes a non-privileged black box test which I think is appropriate here. Naming it after the implementation namespace would make it sound like a unit test or somehow tied to that implementation.

I haven't used midje myself, I've generally been happy with clojure.test so can't comment!

Thanks for the feedback, martian will be much improved!

**Comment by oliyh** [comment]
Hi @orlin 

I've updated `martian-test` so that you can bootstrap it as normal and then convert it into a "test" martian - example [in the readme](https://github.com/oliyh/martian#testing-with-martian-test).

The changes are released as 0.1.5-SNAPSHOT.

Does this cover your use case now?

**Comment by orlin** [comment]
Thanks for the helpful response @oliyh, I've had to put my Clojure projects on hold for a while, so I don't know yet.  I guess I'll get back to you either way about this, in May or June...
